blank_issues_enabled: true
contact_links:
  - name: Submit resources for Public Neurodiversity Support Center?
    url: https://coda.io/form/Add-Neurodiversity-Resource_d43-e9BR1p3
    about: Please go to this specific Coda.io-hosted form instead. Once added, an maintainer from this project will look onto it soon.